disabled_rules:
  - identifier_name
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - shorthand_operator

included:
  - Sources/Verification/CryptoVerificationService.swift
  - Tests/UnitCoreTests/UnitCoreTests.swift
